name: Deployment pipeline

on:
  push:
    branches:
      - master
    pull_request:
      branches: [master]
      types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:3001
      - name: deployment
        if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        uses: akhileshns/heroku-deploy@79ef2ae4ff9b897010907016b268fd0f88561820
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: vast-sea-59806
          heroku_email: snap.emt@gmail.com
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: "patch"
      - name: failure notification
        uses: 8398a7/action-slack@v3
        with: 
          status: ${{ job.status }}
          fields: repo, message, commit, author, took, eventName
        env: 
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          notify_when: 'failure'
      - name: success notification
        uses: 8398a7/action-slack@v3
        with: 
          status: custom
          fields: workflow, job, commit, repo, author, took
          custom_payload: |
            {
              attachments: [{
                color: 'good',
                text: `New version deployed to ${process.env.REPO} (${process.env.COMMIT}) by ${process.env.AUTHOR} build took ${process.env.TIME_TAKEN}`,
              }]
            }
        env: 
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          notify_when: 'success'